import React, { useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Ionicons } from '@expo/vector-icons';
import { api, jsonOptions } from '../api/client';
import { activeOpacity, colors, globalStyles, spacing } from '../theme';

const blank = { label: 'Home', recipient_name: '', phone: '', line1: '', line2: '', city: 'Ramallah', latitude: 31.9038, longitude: 35.2034, delivery_instructions: '', is_default: true };

export default function AddressesScreen({ navigation }) {
  const qc = useQueryClient();
  const query = useQuery({ queryKey: ['addresses'], queryFn: () => api('/addresses') });
  const [editing, setEditing] = useState(null);
  const [form, setForm] = useState(blank);
  const [error, setError] = useState('');
  const save = useMutation({ mutationFn: ({ id, values }) => api(id ? `/addresses/${id}` : '/addresses', jsonOptions(id ? 'PATCH' : 'POST', values)), onSuccess: () => { setEditing(null); setForm(blank); setError(''); qc.invalidateQueries({ queryKey: ['addresses'] }); }, onError: (issue) => setError(issue.message) });
  const remove = useMutation({ mutationFn: (id) => api(`/addresses/${id}`, { method: 'DELETE' }), onSuccess: () => qc.invalidateQueries({ queryKey: ['addresses'] }) });
  const startEdit = (item) => { setEditing(item.id); setForm({ ...item }); setError(''); };
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  return <SafeAreaView edges={['top']} style={globalStyles.screen}>
    <View style={styles.header}><TouchableOpacity style={styles.icon} onPress={() => navigation.goBack()}><Ionicons name="arrow-back" size={22} color={colors.primary} /></TouchableOpacity><Text style={styles.title}>Delivery addresses</Text><TouchableOpacity style={styles.icon} onPress={() => { setEditing('new'); setForm(blank); }}><Ionicons name="add" size={24} color={colors.primary} /></TouchableOpacity></View>
    <ScrollView contentContainerStyle={styles.content}>
      {(query.data || []).map((item) => <View key={item.id} style={[styles.card, item.is_default && styles.cardDefault]}><View style={styles.cardTop}><View style={styles.pin}><Ionicons name="location" size={20} color={colors.primary} /></View><View style={styles.cardText}><Text style={styles.cardTitle}>{item.label}{item.is_default ? ' · Default' : ''}</Text><Text style={styles.line}>{item.line1}{item.line2 ? `, ${item.line2}` : ''}</Text><Text style={styles.line}>{item.city} · {item.phone}</Text></View></View><View style={styles.actions}><TouchableOpacity style={styles.action} onPress={() => startEdit(item)}><Ionicons name="pencil" size={17} color={colors.primary} /><Text style={styles.actionText}>Edit</Text></TouchableOpacity><TouchableOpacity style={styles.action} onPress={() => Alert.alert('Delete address?', 'This address will no longer be available at checkout.', [{ text: 'Cancel' }, { text: 'Delete', style: 'destructive', onPress: () => remove.mutate(item.id) }])}><Ionicons name="trash-outline" size={17} color={colors.error} /><Text style={[styles.actionText, { color: colors.error }]}>Delete</Text></TouchableOpacity></View></View>)}
      {!query.isLoading && !query.data?.length && !editing && <View style={styles.empty}><Ionicons name="map-outline" size={44} color={colors.surface3} /><Text style={styles.emptyTitle}>No saved address</Text><Text style={styles.line}>Add a Ramallah delivery address before checkout.</Text><TouchableOpacity style={styles.button} onPress={() => setEditing('new')}><Text style={styles.buttonText}>Add address</Text></TouchableOpacity></View>}
      {editing && <View style={styles.form}><Text style={styles.formTitle}>{editing === 'new' ? 'Add address' : 'Edit address'}</Text>{[['label','Label'],['recipient_name','Recipient name'],['phone','Mobile number'],['line1','Street and building'],['line2','Apartment / floor'],['city','City'],['delivery_instructions','Delivery instructions']].map(([key, label]) => <View key={key} style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={String(form[key] || '')} onChangeText={(value) => update(key, value)} keyboardType={key === 'phone' ? 'phone-pad' : 'default'} style={styles.input} placeholderTextColor={colors.textMuted} /></View>)}<TouchableOpacity style={styles.defaultRow} onPress={() => update('is_default', !form.is_default)}><Ionicons name={form.is_default ? 'checkbox' : 'square-outline'} size={22} color={colors.primary} /><Text style={styles.defaultText}>Use as default address</Text></TouchableOpacity>{!!error && <Text accessibilityRole="alert" style={styles.error}>{error}</Text>}<View style={styles.formActions}><TouchableOpacity style={styles.cancel} onPress={() => setEditing(null)}><Text style={styles.cancelText}>Cancel</Text></TouchableOpacity><TouchableOpacity disabled={save.isPending} activeOpacity={activeOpacity} style={styles.button} onPress={() => save.mutate({ id: editing === 'new' ? null : editing, values: form })}><Text style={styles.buttonText}>{save.isPending ? 'Saving…' : 'Save address'}</Text></TouchableOpacity></View></View>}
    </ScrollView>
  </SafeAreaView>;
}

const styles = StyleSheet.create({
  header: { height: 68, paddingHorizontal: spacing.screen, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.border },
  icon: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surface }, title: { color: colors.textPrimary, fontSize: 19, fontWeight: '900' }, content: { padding: spacing.screen, paddingBottom: 70 },
  card: { backgroundColor: colors.surface, borderRadius: 20, borderWidth: 1, borderColor: colors.border, padding: 15, marginBottom: 12 }, cardDefault: { borderColor: colors.primary }, cardTop: { flexDirection: 'row', gap: 12 }, pin: { width: 42, height: 42, borderRadius: 21, backgroundColor: colors.primaryDim, alignItems: 'center', justifyContent: 'center' }, cardText: { flex: 1 }, cardTitle: { color: colors.textPrimary, fontSize: 16, fontWeight: '900' }, line: { color: colors.textSecondary, fontSize: 13, lineHeight: 20, marginTop: 3 }, actions: { flexDirection: 'row', gap: 8, borderTopWidth: 1, borderTopColor: colors.border, marginTop: 14, paddingTop: 10 }, action: { minHeight: 44, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', gap: 6 }, actionText: { color: colors.primary, fontWeight: '800' },
  empty: { alignItems: 'center', paddingTop: 80 }, emptyTitle: { color: colors.textPrimary, fontSize: 20, fontWeight: '900', marginTop: 12 }, form: { backgroundColor: colors.surface, borderRadius: 22, padding: 17, borderWidth: 1, borderColor: colors.border }, formTitle: { color: colors.textPrimary, fontSize: 20, fontWeight: '900', marginBottom: 12 }, field: { marginBottom: 12 }, label: { color: colors.textSecondary, fontSize: 12, fontWeight: '800', marginBottom: 6 }, input: { minHeight: 50, borderRadius: 14, backgroundColor: colors.dark, borderWidth: 1, borderColor: colors.surface3, color: colors.textPrimary, paddingHorizontal: 13 }, defaultRow: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 9 }, defaultText: { color: colors.textPrimary, fontWeight: '700' }, error: { color: colors.error, fontWeight: '700', marginTop: 8 }, formActions: { flexDirection: 'row', gap: 10, marginTop: 14 }, button: { flex: 1, minHeight: 52, backgroundColor: colors.primary, borderRadius: 26, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18 }, buttonText: { color: colors.dark, fontWeight: '900' }, cancel: { minHeight: 52, borderRadius: 26, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18, backgroundColor: colors.surface2 }, cancelText: { color: colors.textPrimary, fontWeight: '800' },
});
