import React from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { colors, globalStyles, spacing } from '../theme';

export default function LegalScreen({ navigation }) {
  return <SafeAreaView edges={['top']} style={globalStyles.screen}><View style={styles.header}><TouchableOpacity style={styles.back} onPress={() => navigation.goBack()}><Ionicons name="arrow-back" size={22} color={colors.primary} /></TouchableOpacity><Text style={styles.title}>Terms & privacy</Text><View style={styles.back} /></View><ScrollView contentContainerStyle={styles.content}><Text style={styles.heading}>Customer terms</Text><Text style={styles.body}>Lomi Market provides grocery ordering and store-managed delivery in supported delivery zones. Product availability, prices, delivery fees, and estimated times are confirmed during checkout. Cash is collected when the order is delivered.</Text><Text style={styles.heading}>Privacy summary</Text><Text style={styles.body}>The service uses your phone number to authenticate your account and stores profile, address, cart, order, preference, and device-notification information needed to provide the service. Administrative access is logged. Payment card details are not collected while cash on delivery is the only enabled method.</Text><Text style={styles.heading}>Account requests</Text><Text style={styles.body}>You may request correction or deletion of customer information through Lomi Market support. Some order records may need to be retained for operational or legal obligations.</Text><View style={styles.notice}><Ionicons name="information-circle" size={20} color={colors.primary} /><Text style={styles.noticeText}>Final jurisdiction-specific legal text must be approved by the store owner before launch.</Text></View></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ header: { height: 68, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: spacing.screen, borderBottomWidth: 1, borderBottomColor: colors.border }, back: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center' }, title: { color: colors.textPrimary, fontSize: 19, fontWeight: '900' }, content: { padding: spacing.screen, paddingBottom: 60 }, heading: { color: colors.textPrimary, fontSize: 20, fontWeight: '900', marginTop: 22, marginBottom: 8 }, body: { color: colors.textSecondary, fontSize: 15, lineHeight: 24 }, notice: { marginTop: 28, borderRadius: 18, backgroundColor: colors.surface, padding: 15, flexDirection: 'row', gap: 10 }, noticeText: { flex: 1, color: colors.textSecondary, lineHeight: 20 } });
