import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Plus } from 'lucide-react'
import { useState, type FormEvent } from 'react'

import { api, jsonBody } from '../api/client'
import { ErrorPanel, Field, Loading, Modal, PageHeader, StatusBadge } from '../components/ui'
import type { Driver } from '../types'

type Zone = { id: string; name_en: string; name_ar: string; cities: string[]; delivery_fee: string; free_delivery_threshold: string; minimum_order: string; estimated_minutes_min: number; estimated_minutes_max: number; is_active: boolean }
type Slot = { id: string; label_en: string; label_ar: string; start_time: string; end_time: string; day_offset: number; capacity: number; is_active: boolean }

export function DeliveryPage() {
  const qc = useQueryClient()
  const [zoneOpen, setZoneOpen] = useState(false)
  const [slotOpen, setSlotOpen] = useState(false)
  const [driverOpen, setDriverOpen] = useState(false)
  const zones = useQuery({ queryKey: ['zones'], queryFn: () => api<Zone[]>('/admin/delivery/zones') })
  const slots = useQuery({ queryKey: ['slots'], queryFn: () => api<Slot[]>('/admin/delivery/slots') })
  const drivers = useQuery({ queryKey: ['drivers'], queryFn: () => api<Driver[]>('/admin/delivery/drivers') })
  const createZone = useMutation({ mutationFn: (value: Omit<Zone, 'id'>) => api('/admin/delivery/zones', { method: 'POST', ...jsonBody(value) }), onSuccess: () => { setZoneOpen(false); void qc.invalidateQueries({ queryKey: ['zones'] }) } })
  const createSlot = useMutation({ mutationFn: (value: Omit<Slot, 'id'>) => api('/admin/delivery/slots', { method: 'POST', ...jsonBody(value) }), onSuccess: () => { setSlotOpen(false); void qc.invalidateQueries({ queryKey: ['slots'] }) } })
  const createDriver = useMutation({ mutationFn: (value: Omit<Driver, 'id'>) => api('/admin/delivery/drivers', { method: 'POST', ...jsonBody(value) }), onSuccess: () => { setDriverOpen(false); void qc.invalidateQueries({ queryKey: ['drivers'] }) } })
  if (zones.isLoading || slots.isLoading || drivers.isLoading) return <Loading label="Loading delivery configuration" />
  if (zones.isError || slots.isError || drivers.isError) return <ErrorPanel error={zones.error ?? slots.error ?? drivers.error} />
  return <><PageHeader title="Delivery" description="Control service areas, fees, thresholds and customer time slots." /><section className="split-panels"><article className="panel"><header><div><h2>Delivery zones</h2><p>City-based MVP coverage</p></div><button className="secondary" onClick={() => setZoneOpen(true)}><Plus />Add zone</button></header><div className="compact-list detailed">{zones.data!.map((zone) => <div key={zone.id}><div><strong>{zone.name_en}</strong><span>{zone.name_ar} · {zone.cities.join(', ')}</span></div><div><strong>{zone.delivery_fee} ₪</strong><span>Free over {zone.free_delivery_threshold} ₪</span></div><StatusBadge value={zone.is_active} /></div>)}</div></article><article className="panel"><header><div><h2>Delivery slots</h2><p>Store-managed fulfillment windows</p></div><button className="secondary" onClick={() => setSlotOpen(true)}><Plus />Add slot</button></header><div className="compact-list detailed">{slots.data!.map((slot) => <div key={slot.id}><div><strong>{slot.label_en}</strong><span>{slot.label_ar}</span></div><div><strong>{slot.start_time}–{slot.end_time}</strong><span>Day +{slot.day_offset} · capacity {slot.capacity}</span></div><StatusBadge value={slot.is_active} /></div>)}</div></article><article className="panel"><header><div><h2>Drivers</h2><p>Store-managed delivery staff</p></div><button className="secondary" onClick={() => setDriverOpen(true)}><Plus />Add driver</button></header><div className="compact-list detailed">{drivers.data!.map((driver) => <div key={driver.id}><div><strong>{driver.name}</strong><span>{driver.phone}</span></div><span>{driver.vehicle || 'No vehicle specified'}</span><StatusBadge value={driver.is_active} /></div>)}</div></article></section>{zoneOpen && <ZoneDialog close={() => setZoneOpen(false)} busy={createZone.isPending} error={createZone.error} submit={(value) => createZone.mutate(value)} />}{slotOpen && <SlotDialog close={() => setSlotOpen(false)} busy={createSlot.isPending} error={createSlot.error} submit={(value) => createSlot.mutate(value)} />}{driverOpen && <DriverDialog close={() => setDriverOpen(false)} busy={createDriver.isPending} error={createDriver.error} submit={(value) => createDriver.mutate(value)} />}</>
}

function DriverDialog({ close, busy, error, submit }: { close: () => void; busy: boolean; error: unknown; submit: (value: Omit<Driver, 'id'>) => void }) {
  const [value, setValue] = useState<Omit<Driver, 'id'>>({ name: '', phone: '', vehicle: '', is_active: true })
  return <Modal title="Add driver" close={close}><form className="form-grid" onSubmit={(event: FormEvent) => { event.preventDefault(); submit(value) }}><Field label="Name"><input required value={value.name} onChange={(e) => setValue((current) => ({ ...current, name: e.target.value }))} /></Field><Field label="Phone"><input required placeholder="0599000000" value={value.phone} onChange={(e) => setValue((current) => ({ ...current, phone: e.target.value }))} /></Field><Field label="Vehicle"><input value={value.vehicle} onChange={(e) => setValue((current) => ({ ...current, vehicle: e.target.value }))} /></Field>{Boolean(error) && <div className="form-wide"><ErrorPanel error={error} /></div>}<div className="modal-actions form-wide"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={busy}>Create driver</button></div></form></Modal>
}

function ZoneDialog({ close, busy, error, submit }: { close: () => void; busy: boolean; error: unknown; submit: (value: Omit<Zone, 'id'>) => void }) {
  const [value, setValue] = useState<Omit<Zone, 'id'>>({ name_en: '', name_ar: '', cities: ['Ramallah'], delivery_fee: '7', free_delivery_threshold: '99', minimum_order: '0', estimated_minutes_min: 30, estimated_minutes_max: 45, is_active: true })
  const field = (key: keyof typeof value, next: unknown) => setValue((current) => ({ ...current, [key]: next }))
  return <Modal title="Add delivery zone" close={close}><form className="form-grid" onSubmit={(event: FormEvent) => { event.preventDefault(); submit(value) }}><Field label="English name"><input required value={value.name_en} onChange={(e) => field('name_en', e.target.value)} /></Field><Field label="Arabic name"><input dir="rtl" required value={value.name_ar} onChange={(e) => field('name_ar', e.target.value)} /></Field><Field label="Cities" hint="Comma separated"><input value={value.cities.join(', ')} onChange={(e) => field('cities', e.target.value.split(',').map((item) => item.trim()).filter(Boolean))} /></Field><Field label="Delivery fee"><input type="number" min="0" step="0.01" value={value.delivery_fee} onChange={(e) => field('delivery_fee', e.target.value)} /></Field><Field label="Free delivery threshold"><input type="number" min="0" value={value.free_delivery_threshold} onChange={(e) => field('free_delivery_threshold', e.target.value)} /></Field><Field label="Minimum order"><input type="number" min="0" value={value.minimum_order} onChange={(e) => field('minimum_order', e.target.value)} /></Field><Field label="Minimum ETA minutes"><input type="number" min="1" value={value.estimated_minutes_min} onChange={(e) => field('estimated_minutes_min', Number(e.target.value))} /></Field><Field label="Maximum ETA minutes"><input type="number" min="1" value={value.estimated_minutes_max} onChange={(e) => field('estimated_minutes_max', Number(e.target.value))} /></Field>{Boolean(error) && <div className="form-wide"><ErrorPanel error={error} /></div>}<div className="modal-actions form-wide"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={busy}>Create zone</button></div></form></Modal>
}

function SlotDialog({ close, busy, error, submit }: { close: () => void; busy: boolean; error: unknown; submit: (value: Omit<Slot, 'id'>) => void }) {
  const [value, setValue] = useState<Omit<Slot, 'id'>>({ label_en: '', label_ar: '', start_time: '09:00', end_time: '11:00', day_offset: 0, capacity: 50, is_active: true })
  const field = (key: keyof typeof value, next: unknown) => setValue((current) => ({ ...current, [key]: next }))
  return <Modal title="Add delivery slot" close={close}><form className="form-grid" onSubmit={(event: FormEvent) => { event.preventDefault(); submit(value) }}><Field label="English label"><input required value={value.label_en} onChange={(e) => field('label_en', e.target.value)} /></Field><Field label="Arabic label"><input dir="rtl" required value={value.label_ar} onChange={(e) => field('label_ar', e.target.value)} /></Field><Field label="Start"><input type="time" value={value.start_time} onChange={(e) => field('start_time', e.target.value)} /></Field><Field label="End"><input type="time" value={value.end_time} onChange={(e) => field('end_time', e.target.value)} /></Field><Field label="Day offset"><input type="number" min="0" max="14" value={value.day_offset} onChange={(e) => field('day_offset', Number(e.target.value))} /></Field><Field label="Capacity"><input type="number" min="1" value={value.capacity} onChange={(e) => field('capacity', Number(e.target.value))} /></Field>{Boolean(error) && <div className="form-wide"><ErrorPanel error={error} /></div>}<div className="modal-actions form-wide"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={busy}>Create slot</button></div></form></Modal>
}
