import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Pencil, Plus, Trash2 } from 'lucide-react'
import { useState, type FormEvent } from 'react'

import { api, jsonBody } from '../api/client'
import { Empty, ErrorPanel, Field, Loading, Modal, PageHeader, StatusBadge } from '../components/ui'

type Promotion = { id: string; code: string; name: string; discount_type: 'percentage' | 'fixed'; discount_value: string; minimum_order: string; maximum_discount?: string; starts_at?: string; ends_at?: string; usage_limit?: number; used_count: number; per_user_limit: number; is_active: boolean }
const blank: Omit<Promotion, 'id' | 'used_count'> = { code: '', name: '', discount_type: 'percentage', discount_value: '10', minimum_order: '0', maximum_discount: '50', starts_at: '', ends_at: '', usage_limit: undefined, per_user_limit: 1, is_active: true }

export function PromotionsPage() {
  const qc = useQueryClient()
  const [editing, setEditing] = useState<Promotion | 'new' | null>(null)
  const query = useQuery({ queryKey: ['promotions'], queryFn: () => api<Promotion[]>('/admin/promotions') })
  const save = useMutation({ mutationFn: ({ id, value }: { id?: string; value: Omit<Promotion, 'id' | 'used_count'> }) => api(id ? `/admin/promotions/${id}` : '/admin/promotions', { method: id ? 'PUT' : 'POST', ...jsonBody({ ...value, starts_at: value.starts_at || null, ends_at: value.ends_at || null, maximum_discount: value.maximum_discount || null, usage_limit: value.usage_limit || null }) }), onSuccess: () => { setEditing(null); void qc.invalidateQueries({ queryKey: ['promotions'] }) } })
  const deactivate = useMutation({ mutationFn: (id: string) => api(`/admin/promotions/${id}`, { method: 'DELETE' }), onSuccess: () => void qc.invalidateQueries({ queryKey: ['promotions'] }) })
  if (query.isLoading) return <Loading label="Loading promotions" />
  if (query.isError) return <ErrorPanel error={query.error} retry={() => void query.refetch()} />
  return <><PageHeader title="Promotions" description="Create controlled discounts and usage limits." action={<button className="primary" onClick={() => setEditing('new')}><Plus />Add promotion</button>} /><section className="panel table-panel">{query.data!.length ? <div className="table-scroll"><table><thead><tr><th>Code</th><th>Discount</th><th>Minimum</th><th>Usage</th><th>Schedule</th><th>Status</th><th /></tr></thead><tbody>{query.data!.map((item) => <tr key={item.id}><td><strong className="promo-code">{item.code}</strong><span>{item.name}</span></td><td>{item.discount_value}{item.discount_type === 'percentage' ? '%' : ' ₪'}</td><td>{item.minimum_order} ₪</td><td>{item.used_count}{item.usage_limit ? ` / ${item.usage_limit}` : ''}</td><td>{item.starts_at ? new Date(item.starts_at).toLocaleDateString() : 'Immediately'}<span>{item.ends_at ? `to ${new Date(item.ends_at).toLocaleDateString()}` : 'No end date'}</span></td><td><StatusBadge value={item.is_active} /></td><td className="actions"><button className="icon-button" onClick={() => setEditing(item)} aria-label={`Edit ${item.code}`}><Pencil /></button><button className="icon-button danger" onClick={() => { if (confirm(`Deactivate ${item.code}?`)) deactivate.mutate(item.id) }} aria-label={`Deactivate ${item.code}`}><Trash2 /></button></td></tr>)}</tbody></table></div> : <Empty title="No promotions" message="Create a code when the store is ready to run an offer." />}</section>{editing && <PromotionDialog value={editing === 'new' ? blank : editing} busy={save.isPending} error={save.error} close={() => setEditing(null)} submit={(value) => save.mutate({ id: editing === 'new' ? undefined : editing.id, value })} />}</>
}

function PromotionDialog({ value: initial, busy, error, close, submit }: { value: Omit<Promotion, 'id' | 'used_count'> | Promotion; busy: boolean; error: unknown; close: () => void; submit: (value: Omit<Promotion, 'id' | 'used_count'>) => void }) {
  const [value, setValue] = useState(initial)
  const field = (key: keyof typeof value, next: unknown) => setValue((current) => ({ ...current, [key]: next }))
  const send = (event: FormEvent) => { event.preventDefault(); const payload = { ...value } as Partial<Promotion>; delete payload.id; delete payload.used_count; submit(payload as Omit<Promotion, 'id' | 'used_count'>) }
  return <Modal title={'id' in value ? 'Edit promotion' : 'Create promotion'} close={close}><form className="form-grid" onSubmit={send}><Field label="Code"><input required value={value.code} onChange={(e) => field('code', e.target.value.toUpperCase())} /></Field><Field label="Name"><input required value={value.name} onChange={(e) => field('name', e.target.value)} /></Field><Field label="Discount type"><select value={value.discount_type} onChange={(e) => field('discount_type', e.target.value)}><option value="percentage">Percentage</option><option value="fixed">Fixed amount</option></select></Field><Field label="Discount value"><input type="number" min="0.01" step="0.01" value={value.discount_value} onChange={(e) => field('discount_value', e.target.value)} /></Field><Field label="Minimum order"><input type="number" min="0" step="0.01" value={value.minimum_order} onChange={(e) => field('minimum_order', e.target.value)} /></Field><Field label="Maximum discount"><input type="number" min="0" step="0.01" value={value.maximum_discount ?? ''} onChange={(e) => field('maximum_discount', e.target.value)} /></Field><Field label="Starts"><input type="datetime-local" value={value.starts_at?.slice(0, 16) ?? ''} onChange={(e) => field('starts_at', e.target.value)} /></Field><Field label="Ends"><input type="datetime-local" value={value.ends_at?.slice(0, 16) ?? ''} onChange={(e) => field('ends_at', e.target.value)} /></Field><Field label="Total usage limit"><input type="number" min="1" value={value.usage_limit ?? ''} onChange={(e) => field('usage_limit', e.target.value ? Number(e.target.value) : undefined)} /></Field><Field label="Per customer limit"><input type="number" min="1" value={value.per_user_limit} onChange={(e) => field('per_user_limit', Number(e.target.value))} /></Field><label className="check form-wide"><input type="checkbox" checked={value.is_active} onChange={(e) => field('is_active', e.target.checked)} />Promotion active</label>{Boolean(error) && <div className="form-wide"><ErrorPanel error={error} /></div>}<div className="modal-actions form-wide"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={busy}>{busy ? 'Saving…' : 'Save promotion'}</button></div></form></Modal>
}
