"""add persistent auth throttling

Revision ID: 24604b66c657
Revises: 65ac19f6c485
Create Date: 2026-07-13 03:39:48.635980
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '24604b66c657'
down_revision: Union[str, Sequence[str], None] = '65ac19f6c485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_attempts'))
    )
    op.create_index(op.f('ix_auth_attempts_key_hash'), 'auth_attempts', ['key_hash'], unique=True)
    op.create_index(op.f('ix_auth_attempts_locked_until'), 'auth_attempts', ['locked_until'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_attempts_locked_until'), table_name='auth_attempts')
    op.drop_index(op.f('ix_auth_attempts_key_hash'), table_name='auth_attempts')
    op.drop_table('auth_attempts')
    # ### end Alembic commands ###
